//type常量
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const RESETAGE = 'RESETAGE';
const INCREMENT_ASYN = 'INCREMENT_ASYN';
const DECREMENT_ASYN = 'DECREMENT_ASYN';
const RESETAGE_ASYN = 'RESETAGE_ASYN';
export default { INCREMENT, DECREMENT, RESETAGE, INCREMENT_ASYN, DECREMENT_ASYN, RESETAGE_ASYN };
