//type常量
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const RESETAGE = 'RESETAGE';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const DECREMENT_ASYNC = 'DECREMENT_ASYNC';
const RESETAGE_ASYNC = 'RESETAGE_ASYNC';
export default { INCREMENT, DECREMENT, RESETAGE, INCREMENT_ASYNC, DECREMENT_ASYNC, RESETAGE_ASYNC };
